
server:
  port: 8181
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruian?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password:

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ruian.core.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


#showSql
logging:
  level:
    com:
      ruian:
        core:
         mapper : debug